version: '2'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        version: "0.0.1"
        environment: beta
    ports:
    - "8080:8080"
    entrypoint:
    - npm
    - run
    - dev